#=============================================================#
#                        APPLICATION                          #
#=============================================================#
spring.application.name=bank-service
server.port=8080
#=============================================================#
#                          DATABASE                           #
#=============================================================#
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=dev
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
#=============================================================#
#                           LOGGING                           #
#=============================================================#
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
#=============================================================#
#                          LIQUIBASE                          #
#=============================================================#
spring.liquibase.enabled=true
spring.liquibase.drop-first=false
spring.liquibase.change-log=classpath:db/changelog-master.xml
spring.liquibase.default-schema=public
#=============================================================#
#                          SECURITY                           #
#=============================================================#
jwt.secret.key=46294A404E635266556A586E327235753778214125442A472D4B615064536756
jwt.expiration.time=3600000